
/* generated by: ControllerGenerator Wed May 18 15:20:45 CEST 2016 */
package com.littleworld.todo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Todo {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  int id;
  String task;
  String assignee;
  public Todo() {}
  public Todo(int id, String task, String assignee) {
    this.id = id;
    this.task = task;
    this.assignee = assignee; }
  public int getId() { return id; }
  public void setId(int id)  { this.id = id; } 
  public String getTask() { return task; }
  public void setTask(String task)  { this.task = task; }
  public String getAssignee() {
    return assignee;
  }
  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }
  @Override 
  public String toString() {
    return "[Todo: [" + "id: " + id + ", " + "task: " + task + ", " + "assignee: " + assignee + "]";
  }
}

